FROM guangie88/rustfmt-clippy:nightly-2018-04-18

WORKDIR /app
COPY ./Cargo.toml ./Cargo.lock ./rustfmt.toml ./

RUN set -x \
    && cargo fetch --locked -v

COPY ./src/ ./src/

RUN cargo clippy --all \
    && cargo test --all --no-run
