FROM guangie88/rs-cider:1.27.2

WORKDIR /app
COPY ./Cargo.toml ./rustfmt.toml ./

RUN set -x \
    && cargo fetch -v

COPY ./src/ ./src/

RUN RUSTFLAGS="-D warnings" cargo +nightly clippy --all \
    && cargo test --all --no-run
